### ISSUE TITLE
Documentation: Add examples for an existing Symfony app

### ISSUE THREAD

**Issue by emmetog** [matthiasnoback/symfony-service-definition-validator#31]
I've just come across this project and it looks really interesting! Thanks for releasing it!

I'm just getting started and I'm trying to wire everything together to test the service definitions of my existing Symfony project. The approach I'm taking so far (although if there's a better way please let me know) is to create a single symfony functional test to test all of the service definitions in my project. However I'm not entirely sure how I should wire this together (how do I get the ContainerBuilder/Definition, etc from within my test?).

A few practical examples of how to wire up these tests in an existing Symfony app would be great.

**Comment by emmetog** [comment]
I've managed to get it working by adding the compiler pass to the bundle as described [here](https://github.com/matthiasnoback/symfony-service-definition-validator#compiler-pass). This has the benefit that the app is not usable while there is a problem (so it needs to be fixed immediately) but it would be nicer to be able to run the validation separately, for example by running a symfony console command or by running a specific test.

For now, I'm happy with the compiler pass solution though :)

**Comment by emmetog** [comment]
Created PR https://github.com/matthiasnoback/symfony-service-definition-validator/pull/32

**Comment by matthiasnoback** [comment]
Closing this after merging #32.
