### ISSUE TITLE
You have requested a non-existent service "service_container".

### ISSUE THREAD

**Issue by sstok** [matthiasnoback/symfony-service-definition-validator#36]
Today my build failed with the error shown above.
https://travis-ci.org/rollerworks/RouteAutowiringBundle/jobs/197594167

It seems something is changed in the way Symfony 3.3 handles the `service_container` service reference. But I cannot find out what exactly.

A simple fix is to simple ignore the `service_container` in `\Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator::validateReferenceArgument` but there should be better fix.

Right now I'm unable to use the validator with Symfony 3.3

**Comment by xabbuh** [comment]
The `service_container` service is a bit special (see the handling for it in the built-in `Container` class). I think calling `findDefinition()` for it does not make much sense as their is no definition for the container.

**Comment by sstok** [comment]
I wonder why it worked in the past 😐 was the service_container defined as a synthetic service or something?

**Comment by xabbuh** [comment]
Last night I tried to reproduce your issue, but with older Symfony versions that code path simply wasn't triggered at all. I am not sure though why that is the case. A more restricted example could help to find out whether this is a bug in the validator library or a regresseion in the DependencyInjection component.

**Comment by matthiasnoback** [comment]
I would be all for ignoring that `service_container` service by the way. Happy to merge in a PR :)

**Comment by xabbuh** [comment]
see #37 for a fix
